


* 地质数据
- 一个环段长是1.5米 采样是随机的 数据采样过程如下：比如采样点A落在1081
  环段的0.61米处
- 原始数据是从上到下的地层对应的地质类型编号，和对应的地层厚度。
- 每个类别对应的地质属性有7个。
- 最多统计了5中不同类别的地层。


** 地质转换成矩阵
- 地质数据可以切分成3000层。每层都有对应的类别编号。
- 矩阵连续若干行的值都是一样的。
- 每个矩阵至多只有5个不同的行。
  
因此矩阵是3000*7的矩阵。
* 运行数据
- 运行数据，有标注环段，但是不够准确。之前的做法是通过对速度积分来计算
  环段。
- 运行数据，按说是1秒记录一次，但是也有数据不一致的情况。

- 经验是从采样点，前后取0.30米的运行数据。
** 数据特征分类
*** 温度（3）
- 主油箱油温 TEZ
- 齿轮油油温 TEG
- 螺机油温   TEL
*** 压力（33）
第一组
- 推进压力 FP
- A组推进压力 FPA
- B组推进压力 FPB
- C组推进压力 FPC
- D组推进压力 FPD  

第二组
- 盾尾密封前部右上压力 PDWUR
- 盾尾密封前部正右压力 PDWRR
- 盾尾密封前部右上压力 PDWDR
- 盾尾密封前部左下压力 PDWDL
- 盾尾密封前部正左压力 PDWLL
- 盾尾密封前部左上压力 PDWUL

- 盾尾密封后部右上压力 PDWHUR
- 盾尾密封后部正右压力 PDWHRR
- 盾尾密封后部右下压力 PDWHDR
- 盾尾密封后部左下压力 PDWHDL
- 盾尾密封后部正左压力 PDWHLL
- 盾尾密封后部左上压力 PDWHUL

第三组
- 左上土仓压力 PTUL	
- 上部土仓压力 PTU
- 左下土仓压力 PTDL
- 右下土仓压力 PTDR
- 右上土仓压力 PTUR

第四组
- 左上注浆压力 PZUL
- 右上注浆压力 PZUR	
- 右下注浆压力 PZDR	
- 左下注浆压力 PZDL

第五组
- 螺机泵压力 PL
- 螺机后部压力 PBL
- 螺机前部压力 PFL

第六组 (其他)
- 设备桥压力 PSB
- 铰接压力 PJ
- 膨润土压力 PPLT
- 盾壳膨润土压力 PDPLT
*** 扭矩（2）
- 螺机扭矩 TL
- 刀盘扭矩 T
*** 转速（3）
- 皮带机转速 WP
- 螺机转速 WL
- 刀盘转速 W
*** 位移（8）
- A组推进位移	SA	
- B组推进位移	SB
- C组推进位移	SC
- D组推进位移	SD

- 右上铰接位移	SUR			
- 右下铰接位移	SDR
- 左下铰接位移	SDL
- 左上铰接位移	SUL
*** 角度
- 俯仰角 SITA
- 滚动角 SIGMA
*** 力
- 推力 F
*** 速度
- 推进速度 V
** 按子系统分类：
推进系统（10）： 推进压力 FP
                A组推进压力 FPA
                B组推进压力 FPB
                C组推进压力 FPC
                D组推进压力 FPD
                A组推进位移 SA	
                B组推进位移 SB
                C组推进位移 SC
                D组推进位移 SD
                推力 F

盾尾密封系统（12）：盾尾密封前部右上压力 PDWUR
                    盾尾密封前部正右压力 PDWRR
                    盾尾密封前部右上压力 PDWDR
                    盾尾密封前部左下压力 PDWDL
                    盾尾密封前部正左压力 PDWLL
                    盾尾密封前部左上压力 PDWUL
                    盾尾密封后部右上压力 PDWHUR
                    盾尾密封后部正右压力 PDWHRR
                    盾尾密封后部右下压力 PDWHDR
                    盾尾密封后部左下压力 PDWHDL
                    盾尾密封后部正左压力 PDWHLL
                    盾尾密封后部左上压力 PDWHUL
          
土仓系统（5）：左上土仓压力 PTUL	
               上部土仓压力 PTU
               左下土仓压力 PTDL
               右下土仓压力 PTDR
               右上土仓压力 PTUR

注浆系统（4）：左上注浆压力 PZUL
               右上注浆压力 PZUR	
               右下注浆压力 PZDR	
               左下注浆压力 PZDL
 
螺机系统（6）：螺机泵压力 PL
               螺机后部压力 PBL
               螺机前部压力 PFL
               螺机转速 WL
               螺机油温 TEL
               螺机扭矩 TL 

铰接系统（5）： 右上铰接位移 SUR			
               右下铰接位移 SDR
               左下铰接位移 SDL
               左上铰接位移 SUL
g               铰接压力 PJ

刀盘系统（3）：刀盘扭矩 T
              刀盘转速 W
              齿轮油油温 TEG
其他（8）：
            设备桥压力 PSB
            膨润土压力 PPLT
            盾壳膨润土压力 PDPLT
            皮带机转速 WP 
            俯仰角 SITA
            滚动角 SIGMA
            推进速度 V
            主油箱油温 TEZ

* 问题概述
- 利用（运行数据+）地质数据，来预测一些重要参数的值：F力，T扭矩，V速度。
- 利用运行数据实现对地质特征的智能识别及判断
- 利用运行数据+地质数据，来评估工程的进度

* TODO [0/5] 11.12-11.19迭代
- [ ] 在工作站上整理好数据。大家在校内网远程上可以访问。同时尝试配置反
  向ssh，利用云服务器。
- [ ] 环段数据可视化：参数曲线；地质层可视化图。
- [ ] 运行数据处理：准确位置计算（利用速度进行积分）；有效数据存储（采
  样前点后0.30米作为一个sub-table进行存储）。基于新数据的迁移算法：SVM，
  LASSO，RF。
- [ ] 特征工程：关联性分析，降维，embedding，时序差分。
- [ ] 领域知识描述：现有关系式，补充文档，每个参数的意义说明。

